version: "3.8"
services:
  backend:
    image: familytodocontainer.azurecr.io/backend:latest
    environment:
      POSTGRES_DB: family_todo
      POSTGRES_USER: family_todo_user
      POSTGRES_PASSWORD: family_todo_password
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: familytodocontainer.azurecr.io/frontend:latest
    ports:
      - "5173:5173"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: family_todo
      POSTGRES_USER: family_todo_user
      POSTGRES_PASSWORD: family_todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
