name: Trigger auto deployment for family-todo-app-container-back

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ staging ]
    paths:
    - '**'
    - '.github/workflows/family-todo-app-container-back-AutoDeployTrigger-e12726f1-8559-407e-b160-cc9fce147579.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FAMILYTODOAPPCONTAINERBACK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FAMILYTODOAPPCONTAINERBACK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FAMILYTODOAPPCONTAINERBACK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: familytodocontainer.azurecr.io
          registryUsername: ${{ secrets.FAMILYTODOAPPCONTAINERBACK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FAMILYTODOAPPCONTAINERBACK_REGISTRY_PASSWORD }}
          containerAppName: family-todo-app-container-back
          resourceGroup: family_todo_app
          imageToBuild: familytodocontainer.azurecr.io/family-todo-app-container-back:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


